[2025-01-18T19:18:37.905+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-18T19:18:37.920+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.upload_to_s3 manual__2025-01-18T19:05:27.496917+00:00 [queued]>
[2025-01-18T19:18:37.929+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.upload_to_s3 manual__2025-01-18T19:05:27.496917+00:00 [queued]>
[2025-01-18T19:18:37.930+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-18T19:18:37.943+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2025-01-18 19:05:27.496917+00:00
[2025-01-18T19:18:37.959+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=361) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-18T19:18:37.963+0000] {standard_task_runner.py:72} INFO - Started process 363 to run task
[2025-01-18T19:18:37.961+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'upload_to_s3', 'manual__2025-01-18T19:05:27.496917+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/s3_ingest_dag.py', '--cfg-path', '/tmp/tmph14sif3o']
[2025-01-18T19:18:37.970+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask upload_to_s3
[2025-01-18T19:18:37.995+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-18T19:18:38.030+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion.upload_to_s3 manual__2025-01-18T19:05:27.496917+00:00 [running]> on host 441b7a80a838
[2025-01-18T19:18:38.108+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-01-18T19:05:27.496917+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-18T19:05:27.496917+00:00'
[2025-01-18T19:18:38.109+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-18T19:18:38.131+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-01-18T19:18:38.442+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-01-18T19:34:11.353+0000] {hook.py:208} WARNING - Data lineage tracking is disabled. Register a hook lineage reader to start tracking hook lineage.
[2025-01-18T19:34:11.368+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-18T19:34:11.416+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-18T19:34:11.418+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=upload_to_s3, run_id=manual__2025-01-18T19:05:27.496917+00:00, execution_date=20250118T190527, start_date=20250118T191837, end_date=20250118T193411
[2025-01-18T19:34:11.494+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-18T19:34:11.554+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-18T19:34:11.559+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
